### ISSUE TITLE
Nächstes Meetup / Next Meetup 02.12. 19h

### ISSUE THREAD

**Issue by Spansky** [svelte-meetup-hamburg/meetups#11]
Unser nächstes Meetup startet um 19h. Für Fragen oder Vorschläge könnt Ihr hier kommentieren.

Our next Meetup starts at 1900 MEZ. Questions and ideas can be added as a comment here.

**Comment by Spansky** [comment]
Ich zeige Möglichkeiten auf, wie man Routen in SvelteKit schützen kann. Z.B. wenn jemand eingeloggt ist, soll die Route "/" den Premium-Newsfeed zeigen. Falls der User nicht eingeloggt ist, soll die Landingpage angezeigt werden.

**Comment by kuechlerm** [comment]
Verschoben zum 09.12.

**Comment by nhe23** [comment]
Ich habe eine Frage für das Meetup: Benutzt jemand von euch Sveltekit schon im produktiven Umfeld? Wenn ja, wie sind die Erfahrungen und worauf sollte man achten?
