### ISSUE TITLE
 Nächstes Meetup / Next Meetup 20.01.2022 19h

### ISSUE THREAD

**Issue by Spansky** [svelte-meetup-hamburg/meetups#12]
Unser nächstes Meetup startet um 19h. Für Fragen oder Vorschläge könnt Ihr hier kommentieren.

Our next Meetup starts at 1900 MEZ. Questions and ideas can be added as a comment here.

**Comment by Spansky** [comment]
(for English scroll down further)

Mein Projekt wird immer komplexer. Mit jeder neuen Funktionalität kommen Komponenten, Routen, Endpoints, etc. hinzu. Sicher kennt auch ihr das Problem des wachsenden Codes, der immer schwieriger zu verstehen, zu pflegen und zu erweitern ist und schließlich kaputt geht. 

Das Ziel dieses Meetups ist es, unser Wissen und unsere Best Practices weiterzugeben und einen Einblick zu geben, wie wir unsere Projekte strukturieren, damit sie wartbar bleiben und gleichzeitig elegant und wiederverwendbar sind. Dabei wollen wir insbesondere Svelte-Konzepte wie die Verwendung von Stores, Actions, Layouts, Slots für diesen Zweck genauer betrachten. 

### Agenda: Structuring Svelte Projects
- Which Best Practices have you identified for your Svelte projects?
- Don't repeat yourself (DRY) - Do's and Don'ts - How much can we push this principle before no one can follow anymore? Let's find a compromise between maintainability, elegance and reusability
- Svelte Concepts to refactor code easily: Stores, Actions, Layouts, Slots,... what else is there?

**Comment by kuechlerm** [comment]
Ich musste das Meeting leider nochmal um eine Woche schieben. Hoffe, es passt noch.

**Comment by imperator-maximus** [comment]
Hallo, da das alles online läuft, gibt es doch eigentlich keinen Bedarf an einem "Hamburg Meeting" mehr meiner Meinung nach. Außerdem funktioniert das mit dem Einladungslink eh nicht richtig, so dass mein Interesse hierbei inzwischen gleich Null ist. Wir hätten aber bei dem Thema eigene Erfahrungen beizutragen, da wir wohl die größte Low-Code Custom Elements Plattform auf Svelte Basis aufbauen. Daher die Frage: welche anderen deutschsprachigen Svelte-Online-Meetings gibt es denn sonst noch, die man empfehlen kann?

**Comment by kuechlerm** [comment]
@imperator-maximus Welcher Einladungslink funktioniert nicht?

Das Hamburg Meeting ist nicht komplett vom Tisch. Wenn es die allgemeine Lage wieder zulässt, sind hybride Treffen bei uns im Büro mit Bier, Bagels und Kickern geplant. Online kann man sich aber weiterhin zuschalten.
