### ISSUE TITLE
Nächstes Meetup / Next Meetup 04.03.2021

### ISSUE THREAD

**Issue by kuechlerm** [svelte-meetup-hamburg/meetups#5]
Unser nächstes Meetup startet um 19h. Für Fragen oder Vorschläge könnt Ihr hier kommentieren.

Our next Meetup starts at 1900 MEZ. Questions and ideas can be added as a comment here.

**Comment by Narigo** [comment]
War leider beim letzten Mal nicht dabei. Bleibt das Meetup auf Deutsch oder wird es nun Englisch?
Wer hat Erfahrungen bzw. tieferen Einblick zu SvelteKit? Wie lang dauert's noch? 🙂

**Comment by kuechlerm** [comment]
Hi @Narigo,
grundsätzlich Deutsch, bei Bedarf auch Englisch. Letztes mal war es auf Englisch.

https://www.npmjs.com/package/@sveltejs/kit
Hier kannst Du zumindest den Stand der "alpha" Version verfolgen. Auf dem Svelte-Discord-Server (nicht unserer) kannst Du vielleicht mehr erfahren.
